#MySQL
CREATE TABLE date_member (
	MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MEMBER_USERNAME VARCHAR(50) NOT NULL, 
    MEMBER_NAME VARCHAR(50) NOT NULL,  
    MEMBER_PWD VARCHAR(50) NOT NULL,  
    MEMBER_AGE INT,                         
    MEMBER_GENDER VARCHAR(50),
    MEMBER_EMAIL1 VARCHAR(20),
    MEMBER_EMAIL2 VARCHAR(20),
    MEMBER_TEL1 INT,
    MEMBER_TEL2 INT,
    MEMBER_TEL3 INT,
    MEMBER_ADDRESS1 VARCHAR(40),
    MEMBER_ADDRESS2 VARCHAR(40),
    MEMBER_ZIPCODE INT,
    
    
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROFILE_PIC VARCHAR(100),