CREATE TABLE date_user (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    USER_USERNAME VARCHAR(50) NOT NULL, 
    USER_NAME VARCHAR(50) NOT NULL,  
    USER_PWD VARCHAR(50) NOT NULL,  
    USER_AGE INT,                         
    USER_GENDER VARCHAR(50),
    USER_EMAIL1 VARCHAR(20),
    USER_EMAIL2 VARCHAR(20),
    USER_TEL1 INT,
    USER_TEL2 INT,
    USER_TEL3 INT,
    USER_ADDRESS1 VARCHAR(40),
    USER_ADDRESS2 VARCHAR(40),
    USER_ZIPCODE INT,
    
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROFILE_PIC VARCHAR(100)
);